name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at 00:00 UTC
  workflow_dispatch:      # lets you run it manually

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake (SVG + GIF)
        uses: Platane/snk@v3
        with:
          github_user_name: arun375797
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
            dist/snake.gif

      - name: Publish artifacts to 'output' branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
